# Generated by Django 5.0.6 on 2024-07-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_genero_registro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_usuario',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
